const product_card = [
  {
    id: 1,
    product_name: "Rayes Alpha",
    description: "Hands-free, Hads-on Mushc Experience",
    price: 5,
    currency: "$hr",
    thumb: "./images/1.png",
  },
  {
    id: 2,
    product_name: "Rayes Z30",
    description: "Hands-free, Hads-on Mushc Experience",
    price: 10,
    currency: "$hr",
    thumb: "./images/2.png",
  },
  {
    id: 3,
    product_name: "Rayes X30",
    description: "Hands-free, Hads-on Mushc Experience",
    price: 7,
    currency: "$hr",
    thumb: "./images/3.png",
  },
  {
    id: 4,
    product_name: "Rayes Alpha",
    description: "Hands-free, Hads-on Mushc Experience",
    price: 8,
    currency: "$hr",
    thumb: "./images/1.png",
  },
  {
    id: 5,
    product_name: "Rayes Z30",
    description: "Hands-free, Hads-on Mushc Experience",
    price: 9,
    currency: "$hr",
    thumb: "./images/2.png",
  },
  {
    id: 6,
    product_name: "Rayes X30",
    description: "Hands-free, Hads-on Mushc Experience",
    price: 20,
    currency: "$hr",
    thumb: "./images/3.png",
  },
  {
    id: 7,
    product_name: "Rayes Alpha",
    description: "Hands-free, Hads-on Mushc Experience",
    price: 15,
    currency: "$hr",
    thumb: "./images/1.png",
  },
  {
    id: 8,
    product_name: "Rayes Z30",
    description: "Hands-free, Hads-on Mushc Experience",
    price: 2,
    currency: "$hr",
    thumb: "./images/2.png",
  },
  {
    id: 9,
    product_name: "Rayes X30",
    description: "Hands-free, Hads-on Mushc Experience",
    price: 25,
    currency: "$hr",
    thumb: "./images/3.png",
  },
];
export default product_card;
